version: "3.9"

services:
  pg:
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_USER: ${USERNAME_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${NAME_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbit:
    image: rabbitmq:4.3-management
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # UI
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    extra_hosts:
      - "host.docker.internal:172.21.80.1"
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./DockerfileAPI
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health/live || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10

  consumer:
    extra_hosts:
      - "host.docker.internal:172.21.80.1"
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./DockerfileConsumerWorker
    restart: on-failure
    depends_on:
      pg:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  migrate:
    env_file:
      - .env
    build:
      context: .
      dockerfile: DockerfileAPI
    command: alembic upgrade head
    environment:
      DATABASE_URL: postgres://${USERNAME_DB}:${PASSWORD_DB}@pg:5432/${NAME_DB}
    depends_on:
      pg:
        condition: service_healthy

volumes:
  pg_data:
  rabbit_data:
