"""empty message

Revision ID: 063b5cfd9629
Revises: f1f4701297a3
Create Date: 2026-04-27 18:01:44.313635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063b5cfd9629'
down_revision: Union[str, Sequence[str], None] = 'f1f4701297a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outbox', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='statustask'),
               existing_nullable=False,
                postgresql_using="status::statustask")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outbox', 'status',
               existing_type=sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='statustask'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
